#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-bigblow.setup
#+TITLE: Rizome Communication
* Marketing Checklist
** The Product
We provide stake pool service for owners of Ada cryptocurrency.

*lucid* is telling the story of awakening, enightenment and emancipation.

We draw attention to philosophical and social challenges that blockchain technologies enable to be solved.

We are participating in a paradigm shift towards tranparent, fair and sustainable economy.

*lucid* is pool of visionaries that embrace the new possibilities and are bringing the brave new world to live.
*** What is stake pool?
A stake pool is a reliable server node that focuses on maintenance and holds the combined stake of various stakeholders in a single entity.
Stake pools are responsible for processing transactions and producing new blocks and are at the core of the Cardano proof-of-stake protocol.[fn:4]

Proof of stake is a more energy efficient alternative to commonly known Proof of Work algorithm.
*** What is Cardano / Ada?
Cardano is a decentralized third-generation proof-of-stake blockchain platform and home to the ada cryptocurrency.
It has been designed from the ground up by a team of top engineers and academic experts.

Cardano has a strong focus on sustainability, scalability, and transparency and is a fully open source project that aims to deliver an inclusive, fair, and resilient infrastructure for financial and social applications on a global scale. It is powered by Ouroboros, the ground-breaking proof-of-stake consensus protocol.[fn:5]
*** Competitors
- https://www.cardanowithpaul.com/
  https://www.youtube.com/channel/UCcd9Ts46yNtjHayRPVLl0wQ

- https://digitalfortress.online/
  https://youtube.com/digitalfortress

- https://cheapstaking.com/

** Marketing strategy
This section outlines guidelines for creating marketing strategy. [fn:1]
Can be improved and populated.
*** Set goals
**** raise brand awareness

Communicate the brand vision and highlight our low fees through posts on Instagram, Facebook, Twitter, Medium, and Reddit. Develop regular content to post on these platforms. 

**** aqcuire new customers

Social media presence - Reddit, Medium, Instagram, Twitter, and Facebook posts, paid ads, crypto influencer marketing campaigns. Engage in the comments, possibly enagage in discussions on popular crypto feeds. 


*** target audience

Crypto enthusiasts who are already involved in the space and looking for reliability / low fees. New users who are interested in crypto, but are hesitant to get started due to its environmental criticisms. People who think they need to invest a considerable amount to get started with Cardano stake pools. 

**** what are we offering to you?

We are supremely confident in our ability to provide a seamlessly working and transparent stake pool with a forward-thinking vision. We do not make compromises when it comes to our user-oriented policies, equipment, and technological solutions. We use high-grade hardware, as well as multiple backup servers to guarantee a smooth workflow. All of our inner company workings are available to our users to ensure complete trust in the company. 

**** what makes us unique?

Ideologically, we believe that Cardano has the potential to be a game-changer in the crypto space and beyond. However, its successful long-term implementation requires innovative solutions. We are aware of the main criticism that cryptocurrencies are encountering, namely the negative impact on the global carbon footprint. The environment is something that we are deeply passionate about. What makes us unique, is that we translate our hope for a bright future into action. X% of our proceeds are donated to support smart eco-friendly causes, such as planting new trees, educating people, and cleaning up polluted areas. We are also working to power our stake pool exclusively with renewable energy. You can access our plans for our Rizome / Lucid Garden here (LINK). By siding with us, you can rest assured that you will enjoy competitive fees, a maximum return on your assets, and aid the environment while doing so. 

**** why would you choose us over competitors?

We see Rizome as an ideological movement, rather than just a company. Our approach combines a strong, philosophically motivated vision, eco-friendly technology, and an overall strive for aiding in the great challenge of creating a society in which humanity can access the most fulfillment. In our view, a fruitful future encompasses financial liberation, an ethically driven value system, and excellent education. We see the world and every creature as worthy of living respectably and freely. This may be a dream for now, but we will only reach it by placing one mindful step after another. Rizome aims to be a force that actively fuels the global shift for a better future by employing a pragmatically minded approach. That encompasses providing free education content, helping to replenish the environment, and proudly carrying the flag of a fully transparent stake pool that is powered exclusively with renewable energy. 


**** B2B -> benefit to business  of certain size or within industry?
**** B2C -> preferred audience based on location, demographics, or interests?
*** Find a place in the market
**** market research - too narrow focus? correct position to reach the right people.
** Reach
This section highlights the actionable items.
To be expanded and more specific
*** Landing Page
**** [ ] collect emails
**** [ ] quick overview
*** Social
**** [ ] scheduled posts
**** [ ] engaging twitter with questions / contraversial statements
**** [ ] reddit posts
**** [ ] medium posts
*** Content Marketing
**** blog posts
**** videos
**** [ ] [#A] infographics
** Target Audience
highlights two primary segments.
*** Ada holders
**** Transparent tech stack
**** Dedicated on-site hardware
**** Additional backup servers to ensure zero downtime and overcome network outages
**** Good cause - low carbon footprint, idealistic future vision with the aim of implementing a fully green operation (rizome garden)
**** No clear benefit compared to other pools
*** Independent investors that are aware of crypto but not necessary into Ada
**** High risk advetureous
**** Fast ROA (+5% per 2 weeks)
*** TODO Market niche
Describe a narrow segment within our target audience.

** Measure success of marketing
*** analytics.google.com (lucidedstakes@gmail.com)
tracks interactions with website (rizome.io and lucid.rizome.io)
*** Delegator count and delegation amount
denotes directly acquired customers
* Brand / Product
** What is rizome.io
*rizome.io* is a company brand that is behind the *lucid* stake pool
** What is lucid
*lucid* is a stake pool service (the product)
** Headlines
*** Blockchain Consulting, Reseach & Solutions
*** Architecture for distributed ledger tech
We provide reliable design and infrastructure solutions for projects powered by blockchain.

** Value proposition
*** Mission
**** Reference: Cardano :noexport:
#+begin_quote
We want Cardano to become the future financial and social operation system for the generations to come.
#+end_quote
**** rizome.io
#+begin_quote
Improve adoption of sustainable blockchain technologies by providing secure, scalable and innovative solutions to financial and social operation challenges.
#+end_quote

**** lucid.rizome.io
#+begin_quote
Provide a best ROI stake pool service for our delegators with an environmentally aware and responsible stake pool operation running on on renewable and green energy.
#+end_quote

*** Why?
We believe that a strong theoretical foundation and forward-thinking planning skills are the bedrock for a sustainable and reliable system. That is why we decided to support the Cardano project - it follows formal specifications, peer-reviewed protocols, and a scientific methodology in its development. [fn:2]

Years of successful work, deep research, and timely updates behind the Cardano technology have proven a meticulous commitment to high values. It established a powerful direction for creating a secure foundation for decentralized value management that is set to open up the doors for paradigm-shifting technologies and interactions powered by blockchain.
*** How?
Rizome.io aligns with the technological stack of the Cardano Foundation that utilizes the practices and tools from the Cardano core codebase.
We embrace and apply these to our infrastructure and tech solutions.

With over a decade of experience gained in software development and years actively involved in the blockchain space, we have proudly earned the expertise necessary for building and maintaining infrastructures for large-scale systems.
Rizome.io represents the fruition of hard work and scrupulous study that lead us to our core values.
We especially highlight the importance of reproducible builds and flexible testability.
After a long journey of dedication, we are excited to provide our users with an exceptional user experience that breathes life into paradigm-shifting ideas.

*** What?
Lucid.rizome.io is a stake pool running on a dedicated Ryzen 7 4800H machine with additional backup servers in multiple locations.
We are proud to guarantee high availability and resilience against power and connection outages. Our competitive fees ensure a high return of assets for our users.


** TODO Roadmap
** Lucid Pool story.
The Lucid Pool is in operation to provide a modern, environmentally conscious infrastructure for the research and development of Cardano-based projects. The minimum fee of 340 and the margin of 1%  ensure competitive rewards for delegators until the pool builds a reputation and history of flawless uninterrupted operation.

The current setup is a hybrid of nodes running on the cloud to ensure reliability. Additional local machines provide extra security and the potential for continuously expanding the operation.

As an environmentally aware organization, we make it our top priority to ensure a minimal carbon impact. Our hardware setup is optimized with that in mind, thus reaching a superb efficiency of operation while also fulfilling the requirements for a Cardano node stake pool.
We are currently fine-tuning the setup to make sure that it keeps up to the high standards we have set as a company. We plan to migrate the primary block production to our in-house solution as soon as we have completed our testing phase. Until then, we are using state-of-the-art cloud-provisioned machines.

We plan that the pool rewards will cover the operating costs and provide enough resources to fund additional developer tools. We also aim to invest in open-source projects that we feel are in high demand within the Cardano community. The emergence of Plutus, smart contracts, and native-tokens is driving the flow of developers and the blockchain community to start using the Cardano network. Our goal is to facilitate a smooth adoption by providing excellent tools and the know-how required for integrating with the Cardano blockchain

In 2021 we are primarily focused on improving the infrastructure and tools for the stake pool operation. That envelops the development of documentation, learning materials, bootstrap scripts, monitoring configurations, ensuring security, resilience, and an overall smooth autonomous operation.

** Mission
#+begin_quote
Of course I want my investments to give me a good roi but more importantly, I want a part in helping change this world 🌎 for the better. I truly believe that Cardano is the best vehicle for major positive change.

#+end_quote
[fn:3]
* Introduction to Lucid
** Andy
I was fascinated by server infrastructure since my early adolesence
when I started this journey with hosting an mmorpg game server.
It has been a long ride throughout time working on social platforms ([[https://heal.me][heal.me]]),
blockchain/networking/privacy based projects ([[https://mysterium.network][mysterium.network]]),
and my current gig with security and architecture for a
major support and natiral language processing whitelabel company.

What excites me most about the blockchain technology is the freedom
it brings from dicatorship of the men in power.
I was doing a bit of research into self-sustaining communities, and the
challenges they were facing. This research could be summarized in the idea
that we should be embracing the knowledge/progress and new technologies
making it serve the society.

The other passion of mine is getting close to earth, nature and my inner
self.
That is excercising conscious activities, spending time in the woods doing nothing, observing my emotions and calming my brain.
Being transparent about my thoughts, feelings with myself, with friends and family.
This might seem not much, but I'm not tracking a score here, this already
feels big from the personal perspective.

Not long time ago I decided to take a piece of land, forest and take care of it.
My dream is to create a forest garden, a place where anyone can find piece,
and learn the simple lessons nature has to offer. My aim is to create
permaculture ecosystem that would grow and evolve, being able to sustain
and fruitful with the least of human intervention that is possible.

* Rizome Introduction
** Lucid Stake Pool Intro 
We are incredibly excited to announce the launch of our Cardano stake pool called Lucid. It has been a passion project that has been long in the works, built with extreme care and a long-term vision in mind. Finally, we are ready to present it to the community.  

As promising as Cardano is in itself, we are confident that the upcoming launch of smart-contract integration has the potential to completely change the game. We have built our stake pool infrastructure with that in mind. On the technological side, our servers are bulletproof.  In the near future we plan to run them exclusively on sustainable energy. We made them as efficient as possible, with additional stand-alone backup machines ready to go, in case of any emergency situation. That guarantees our stake-holders a service that is effortless and reliable 24/7. Once you join our pool, you can rest assured that everything is going to be taken care of. Our fundamentals are solid, and that is a beautiful start. However, our mission is bigger than that. 

We pride ourselves at the fact that Lucid is more than just a stake pool. It is designed to be one leg of our Rizome operation, which encompasses a host of projects aimed at providing free education, supporting environmentally replenishing causes, and aiding in the global financial paradigm-shift that Cardano is capable of fuelling.  

The focus on spreading free educational content is amongst our highest priorities. The technology behind Cardano is incredibly promising. We are sitting on gold, yet the conversations around it are still a niche for technological enthusiasts. It is our mission to help more people to understand the deep implications of what the implementation of this technology could do to advance our transactions, and ultimately, our society. Such an advancement could not only revolutionize our financial systems, but we believe that the potential applications could also have a significant impact on people’s mental freedom and approach to life. Eventually, that has the power to change the world, one perspective at a time.

 It might seem that this is wishful thinking, but we are practical idealists at heart. Global changes get sparked by forward-thinking ideas before they turn into actions. Social media is an excellent tool that we have to hone that. Just like a blade, one can use it for constructive purposes, or for destructive ones. Our aim is to spread life-giving lessons through the power of social networks. Lucid is geared to be a fan for the philosophically oriented sparks that touch upon what it means to be a human in the twenty first century, and the conscious navigation of the multitude of challenges and opportunities in our technologically potent world. In our view, being healthy, smart and capable in such an environment should encompass a knowledge of self, emotional intelligence, and technological savviness. We think that is especially important to instill inspiring ideas to the younger generation in an understandable and welcoming way. That is why a part of our operation is centered around giving people bite-sized lessons on concepts that work to expand and sharpen one’s mind. That encompasses the insights of classical philosophers, practical mental-health lessons, and tips on navigating the technological and financial landscapes of today.

** Rizome Garden

Another important aspect for us is operating in an environmentally conscious, and constructive way. Apart from eventually running exclusively on green energy, we have plans to expand upon that notion. Currently, we have started to build our Rizome Garden. It is a space out in a remote location which will be a multi-purpose hub of activity. It will become the headquarters of our operation, a place for gathering of like-minded people, and a place for the production of green energy. 
**  Andy Novokov 
 Our head of operations is Andy Novokov. He has been fascinated with server infrastructures since he was a teenager. His passion lead him to build and host MMORPG game servers for the love of it. Later on he delved deeper into programming and the study of IT. Nowadays, he works with a major support and natural language processing whitelabel company where he is in charge of security and the maintenance of the overall tech architecture. On the side, Andy was always interested in blockchain technology. Ultimately, his excitement for its liberating potentials culminated in Rizome, and the Lucid Stake pool. He is closely knit and active in the blockchain community, helping to advance the fluid integration of Alonzo and … .   

In the future, Andy dreams of creating a futuristic garden which will host the Rizome servers, events, and be a welcoming haven where like-minded people can come together – virtually and in person. The piece of land has already been secured, but big things don’t happen overnight. We take it one planned step at a time. If you have any questions, don’t hesitate to shoot Andy a message. He is a sociable person who loves to connect with others who are keen to learn and push blockchain technology forward. Our Lucid pool is meant to be personable. We strive to build relationships, and most importantly, a kind community where everybody is welcome to share their ideas, learn, and grow together.

If you choose to join our pool, know that you will be welcomed with open arms. It is built on solid technological foundations, an excitement for the future, and a deep love for bettering humanity. We cannot wait for you to experience what we have in store for you. Our team is available to answer your questions everyday from 9-18 (GMT+2).

Godspeed, friends,
Your Lucid Team

* Footnotes

[fn:5] https://docs.cardano.org/
[fn:4] https://iohk.zendesk.com/hc/en-us/articles/900001951526-What-is-a-stake-pool-

[fn:3] [[https://www.youtube.com/watch?v=K4i-rTNyBWE][The Cardano Foundation Strategy 2021 - YouTube]]
[fn:2] https://why.cardano.org/en/science-and-engineering/the-art-of-iteration/

[fn:1] https://mailchimp.com/resources/startup-marketing-strategy/
