#+TITLE: rizome.io marketing path
* Marketing Checklist
** Marketing strategy
This section outlines guidelines for creating marketing strategy. [fn:1]
Can be improved and populated.
*** Set goals
**** raise brand awareness
**** aqcuire new customers
*** target audience
**** what are you offering to your potential customers?
**** what makes you unique?
**** why would customers choose you over competitors?
**** B2B -> benefit to business  of certain size or within industry?
**** B2C -> preferred audience based on location, demographics, or interests?
*** Find a place in the market
**** market research - too narrow focus? correct position to reach the right people.
** Reach
This section highlights the actionable items.
To be expanded and more specific
*** Landing Page
**** [ ] collect emails
**** [ ] quick overview
*** Social
**** [ ] scheduled posts
**** [ ] engaging twitter with questions / contraversial statements
**** [ ] reddit posts
**** [ ] medium posts
*** Content Marketing
**** blog posts
**** videos
**** [ ] [#A] infographics
** Measure success of marketing
*** analytics.google.com (roastedstakes@gmail.com)
tracks interactions with website (rizome.io and roast.rizome.io)
*** Delegator count and delegation amount
denotes directly acquired customers
* Marketing
** Target Audience
highlights two primary segments.
*** Ada holders
**** Transparent tech stack
**** Dedicated on-site hardware
**** Additional backup servers to ensure zero downtime and overcome network outages
**** Good cause - low carbon footprint, idealistic future vision with the aim of implementing a fully green operation (rizome garden)
**** No clear benefit compared to other pools
*** Independent investors that are aware of crypto but not necessary into Ada
**** High risk advetureous
**** Fast ROA (+5% per 2 weeks)
*** TODO Market niche
Dscribe a narrow segment within our target audience.

* Rizome.io
** Headlines
*** Blockchain Consulting, Reseach & Solutions
** TODO Value proposition
*** IDEA bridging the gap for business use case of DLT
** TODO Roadmap
** Roast Pool story.
The Roast Pool is in operation to provide a modern, environmentally conscious infrastructure for the research and development of Cardano-based projects. The minimum fee of 340 and the margin of 1%  ensure competitive rewards for delegators until the pool builds a reputation and history of flawless uninterrupted operation.

The current setup is a hybrid of nodes running on the cloud to ensure reliability. Additional local machines provide extra security and the potential for continuously expanding the operation.

As an environmentally aware organization, we make it our top priority to ensure a minimal carbon impact. Our hardware setup is optimized with that in mind, thus reaching a superb efficiency of operation while also fulfilling the requirements for a Cardano node stake pool.
We are currently fine-tuning the setup to make sure that it keeps up to the high standards we have set as a company. We plan to migrate the primary block production to our in-house solution as soon as we have completed our testing phase. Until then, we are using state-of-the-art cloud-provisioned machines.

We plan that the pool rewards will cover the operating costs and provide enough resources to fund additional developer tools. We also aim to invest in open-source projects that we feel are in high demand within the Cardano community. The emergence of Plutus, smart contracts, and native-tokens is driving the flow of developers and the blockchain community to start using the Cardano network. Our goal is to facilitate a smooth adoption by providing excellent tools and the know-how required for integrating with the Cardano blockchain

In 2021 we are primarily focused on improving the infrastructure and tools for the stake pool operation. That envelops the development of documentation, learning materials, bootstrap scripts, monitoring configurations, ensuring security, resilience, and an overall smooth autonomous operation.

** Rizome.io Brand awareness
*** Why?
Purpose, cause, and belief. Why does the company exist?
We believe that a strong theoretical foundation and forward-thinking planning skills are the bedrock for a sustainable and reliable system. That is why we decided to support the Cardano project - it follows formal specifications, peer-reviewed protocols, and a scientific methodology in its development. [fn:2]

Years of successful work, deep research, and timely updates behind the Cardano technology have proven a meticulous commitment to high values. It established a powerful direction for creating a secure foundation for decentralized value management that is set to open up the doors for paradigm-shifting technologies and interactions powered by blockchain.
*** How?
Rizome.io aligns with the technological stack of the Haskell Foundation that utilizes the practices and tools from the Cardano core codebase. We embrace and apply these to our infrastructure and tech solutions.

With over a decade of experience gained in software development and years actively involved in the blockchain space, we have proudly earned the expertise necessary for building and maintaining infrastructures for large-scale systems. Rizome.io represents the fruition of hard work and scrupulous study that lead us to our core values. We especially highlight the importance of reproducible builds and flexible testability. After a long journey of dedication, we are excited to provide our users with an exceptional user experience that breathes life into paradigm-shifting ideas.

*** What?
Roast.rizome.io is a stake pool running on a dedicated Ryzen 7 4800H machine with additional backup servers in multiple locations. We are proud to guarantee high availability and resilience against power and connection outages. Our competitive fees ensure a high return of assets for our users.

* Footnotes
[fn:2] https://why.cardano.org/en/science-and-engineering/the-art-of-iteration/

[fn:1] https://mailchimp.com/resources/startup-marketing-strategy/
